### ISSUE TITLE
Midi channel

### ISSUE THREAD

**Issue by olibac** [essej/sonobus#26]
Is it possible to have a midi input channel and add and VSTi to this midi channel?
I am a drummer and I would like to use my e-drums to trigger Superior Drummer.
Thanks for your great efforts!

**Comment by essej** [comment]
For now you can use the plugin version of SonoBus in another application (like a DAW or other plugin host) and add SonoBus to the master bus, so you can have much more than just one thing going in (you could set up  your Superior Drummer on one track, and vocal input on another, mix them, add effects, etc), with that mix being sent to remote people in SonoBus.  Reaper is good host for this kind of thing.

That said, it might be possible to add some simple plugin hosting support in the standalone SonoBus, but because I provide a plugin version, this isn't a high priority...

**Comment by olibac** [comment]
Ok, thanks a lot for you prompt answer!
