### ISSUE TITLE
Ardour is blacklisting Sonobus VST plugin

### ISSUE THREAD

**Issue by Samgarr** [essej/sonobus#41]
Hello!
I tried to use Sonobus VST plugin with Ardour 6.3.0, but Ardour is blacklisting this plugin:
```
2021-02-17T14:15:55 [INFO]: VST Blacklist:
/usr/local/lib/vst3/SonoBus.vst3/Contents/x86_64-linux/SonoBus.so
/usr/lib/vst/carla.vst/libcarla_native-plugin.so
/usr/lib/vst/carla.vst/libcarla_interposer-safe.so
/usr/lib/vst/carla.vst/carla-bridge-lv2.so
/usr/lib/vst/carla.vst/libcarla_utils.so
/usr/lib/carla/styles/carlastyle.so
/usr/lib/vst/carla.vst/libcarla_interposer-jack-x11.so
/usr/lib/vst/carla.vst/libcarla_interposer-x11.so
```
With Carla or Bitwig plugin is working, but Ardour have some issue. If i can provide more info please let me know, i'm not much experienced with audio or DAW ecosystems on linux.

**Comment by derwok** [comment]
Hi, try Ardour 6.5 - for me SonBus shows up there.
The Ui is reacting quite slow... but it works...

![image](https://user-images.githubusercontent.com/4393698/108623988-49d08d00-7442-11eb-9645-7e93e921a2b6.png)

![image](https://user-images.githubusercontent.com/4393698/108624022-7684a480-7442-11eb-9cc7-5e1945f2cafa.png)

**Comment by derwok** [comment]
Suggestion to close this issue here.

**Comment by LGCW** [comment]
The UI in Ardour is not really usable due to the slowness. Standalone if fine.

**Comment by Samgarr** [comment]
Ardour 6.6 - Sonobus can be inserted as plugin but makes whole Ardour slow, barely usable.

**Comment by ericfont** [comment]
I can verify it is possible to use SonoBus VST in Ardour 6.6 on Linux, but it seems its GUI can be very unresponsive.  And Alt-tabbing out and then tabbing back in a minute later will cause it to hang forever.

On my Arch Linux 12-core desktop, on a fresh start of Ardour with a new project without any plugins the top command shows Ardour using around 4% of a core.  After I add the Sonobus plugin, Ardour usage jumps to 13% of a core.  But then opening the GUI results in Ardour using around 75% of a core and Xorg usage going up from around 1% to an ridiculous 60% of a core.

The Ardour developer says Ardour has a deliberate design to always run all plugins even without input:
> Ardour runs all it plugins continuously by design. It might be less energy efficient than switching them off when there is no input, but that way there are no surprises where your dynamic usage suddenly goes over the available CPU time in the middle of a mix.

I wonder if maybe this aspect of Ardour's design is contributing to that high CPU usage somehow.

(I have wondered if SonoBus would work better as LV2 plugin inside Ardour due to LV2's separation of GUI vs audio processing.  There is a fork of JUCE that can build LV2: https://github.com/DISTRHO/JUCE)

Out of curiosity I'm going to reboot to windows and see if I notice similar CPU usage.

**Comment by Spacechild1** [comment]
> I wonder if maybe this aspect of Ardour's design is contributing to that high CPU usage somehow

I don't think so. Even if the plugin is running all the time, there shouldn't be such high CPU usage.

> I have wondered if SonoBus would work better as LV2 plugin inside Ardour due to LV2's separation of GUI vs audio processing. 

VST3 also has a rather strict seperation between GUI and audio processing.

I think this is rather an issue with (the usage of) the JUCE wrapper and/or Ardour's UI handling. I have seen similar high CPU usage even on Windows in REAPER with some earlier versions of the IEM ambisonics plugin suite (https://plugins.iem.at/). (It has been resolved in the meantime, but I don't know what the problem was. You would have to ask the devs.)

Also, it may be interesting to test SonoBus with Ardour on non-Linux platforms and compare the results. If the high CPU usage only shows on Linux, it is a platform specific issue which most likely points a problem with the UI code (on either side).

**Comment by ericfont** [comment]
ok, tried on windows on same machine, same version of Ardour 6.6 and same version of SonoBus 1.3.6 beta VST3 plugin.  Windows Task Manager says Ardour alone uses just under 1% total processsor utilization.  When I add SonoBus VST without GUI open, Ardour CPU usage is around 1.4% total processsor utilization.  When I open SonoBus VST's GUI, cpu usage only goes to around 1.7% total processsor utilization.

Ardour and SonoBus GUI seems quite response in Windows, unlike in Linux.  So this GUI issue in Ardour seems to only happen in Linux.  The high XOrg usage might be indicative of something.

(Note Linux top measures in percent of a virtual cpu which is one hyperthread of a core, while Windows Task Manager measures in percent of total processor which is all cores, so it is not easy to directly compare those Linux vs Windows numbers)

**Comment by ericfont** [comment]
> VST3 also has a rather strict seperation between GUI and audio processing, at least from the SDK point of view, but maybe JUCE does some sketchy things.

aha...so reading online it sounds likes VST2 did not have separation between GUI & audio, but VST3 does.  And also I'm reading on Juce forums that "Juce has no concept for separating the GUI and data/DSP into different processes".

**Comment by Spacechild1** [comment]
> so reading online it sounds likes VST2 did not have separation between GUI & audio, but VST3 does

Correct.

> "Juce has no concept for separating the GUI and data/DSP into different processes".

I'm not super familiar with JUCE, but I think it splits the plugin into an editor and processor class. However, they share data and therefore have to run in the same process (albeit on different threads).

The VST3 SDK completely separates editor and processor and they can only communicate via message (which has to be done by the host),. This means they can really run in different processes - or even on different machines!

**Comment by ericfont** [comment]
As far as I can gather, this GUI hang is only happening in Ardour in Linux.  So it seems at this point to be a bug in Ardour's Linux code.  So I've forwarded this report to them here: https://discourse.ardour.org/t/sonobus-vst3-gui-hogs-cpu-only-when-ran-inside-ardour-on-linux-but-not-windows/105573

I'm closing this github issue because the original issue was completely separate (Ardour blacklising SonoBus) and doesn't seem to be happening any more since Ardour version 6.5
