### ISSUE TITLE
Linux standalone - Connect button not activating

### ISSUE THREAD

**Issue by jcrystal** [essej/sonobus#8]
Hello team!

I've complied SonoBus (which, tbh, is incredible) on Linux Debian (stretch), and there seems to be an oddity with the way certain buttons are [not] responding. Not sure if this is a JUCE issue or a SonoBus issue, but...

In the Connect > Group pane, after entering in some credentials, clicking "Connect to Group" doesn't result in any change in the GUI beyond the depressing/color-change of the button (nor is there indication that a new user has connected from the other Mac/Windows folks in the group).

If I repeatedly click Connect to Group, the terminal window which spawned the app says `aoo_client: already connecting!`, but that's all.

Screenshot attached. Any idea how I might help determine where/how the process is collapsing? Is there a good spot to look for helpful logs?

Thanks!

-Jason

<img width="1175" alt="Screen Shot 2020-11-08 at 10 43 59 AM" src="https://user-images.githubusercontent.com/20938/98469859-137f4280-21b0-11eb-81ff-e2081a911671.png">

**Comment by essej** [comment]
Yeah, this happens when the audio processing code isn’t being run by the audio driver. What is your audio setup? If using jack you need to make sure it’s running and apparently you also need to connect some ports. If using ALSA directly, you have to select input and output interfaces. 

Obviously this needs to be smoothed out, and I should recognize when it’s happening so a proper error message can be shown.

**Comment by jcrystal** [comment]
That was absolutely it. Totally nailed it; thanks!

Just needed to get Jack up and rolling, and confirm the patching.
